# Generated by Django 4.1.1 on 2022-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='group',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='starting_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
