# Generated by Django 4.1.1 on 2022-09-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_group_options_alter_sticker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
