# Generated by Django 4.1.1 on 2022-09-27 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0004_sticker_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sticker',
            unique_together={('number', 'team', 'owner')},
        ),
    ]
